; PlatformIO Project Configuration File

[platformio]
default_envs = hardware

; Environment cho Giả lập Wokwi
[env:wokwi]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DDHT_SENSOR_TYPE=DHT22
build_src_filter = +<*> -<rfid_test.cpp>
monitor_speed = 115200
monitor_port = socket://localhost:4000
monitor_filters = esp32_exception_decoder, direct
lib_deps =
    knolleary/PubSubClient
    marcoschwartz/LiquidCrystal_I2C
    adafruit/DHT sensor library@^1.4.6
    madhephaestus/ESP32Servo@^3.2.1
    miguelbalboa/MFRC522

; Environment cho Mạch ESP32 Thật (Cắm cáp USB vào máy tính)
[env:hardware]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DMFRC522_SPICLOCK=1000000u -DDHT_SENSOR_TYPE=DHT11
build_src_filter = +<*> -<rfid_test.cpp>
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, direct
upload_port = COM6
monitor_port = COM6
lib_deps =
    knolleary/PubSubClient
    marcoschwartz/LiquidCrystal_I2C
    adafruit/DHT sensor library@^1.4.6
    madhephaestus/ESP32Servo@^3.2.1
    miguelbalboa/MFRC522

; Minimal hardware diagnostic: ESP32 + RC522 only
[env:rfid_test]
extends = env:hardware
build_src_filter = -<*> +<rfid_test.cpp>
